### ISSUE TITLE
Create Mobile Mockups

### ISSUE THREAD

**Issue by oguzsenna** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1-mobile#10]
I started making mockups on figma there is the link :

https://www.figma.com/file/uYsmFIA0eHKg63wWICI326/Mobile-App-Design-System-UI-Kit-%C2%B7-Free-(Community)?type=design&node-id=2124%3A9969&mode=design&t=CbWPLS61PDxCRiNp-1

**Comment by oguzsenna** [comment]
I created the milestone 1 desings 

https://www.figma.com/file/uYsmFIA0eHKg63wWICI326/574-UI-KIT?type=design&node-id=2124%3A9969&mode=design&t=sYfKHB8VKYecAJSS-1

**Comment by ayhncvdr2** [comment]
@oguzsenna Can we create a general popup design? We also need to show something when there is no connection for home and feed page (maybe the logo and below a text saying that "there is no connection" or something like that)

**Comment by oguzsenna** [comment]
<img width="650" alt="Screenshot 2023-10-28 at 18 43 57" src="https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1-mobile/assets/93736051/01549dee-3f6c-4173-acb0-26b11c579605">
Are these okey ? We can work on the color scheme if you want .

**Comment by ayhncvdr2** [comment]
ok we can add it in in milestone 2, we have a simple popup for milestone 1
