### ISSUE TITLE
Discord Webhook to follow GitHub activities

### ISSUE THREAD

**Issue by sadikkuzu** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1-mobile#11]
As in SWE574-Fall2023-Group1/SWE574-Fall2023-G1#4
we may have Discord Webhook to follow GitHub activities for mobile repo too.

**Comment by ckertam** [comment]
Done in discord 🤖

**Comment by sadikkuzu** [comment]
Cool ✨ thank you 👏🏼
