### ISSUE TITLE
Activity Stream design improvements

### ISSUE THREAD

**Issue by ayhncvdr2** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1-mobile#110]
The design of activity stream page should be improved. Now, only static list is displayed like below screenshot:

![image](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1-mobile/assets/116437926/7ecdc0f2-b0c1-44f4-b7bb-ad80333c60f2)

**Comment by aykutkantas** [comment]
@ayhncvdr2 Activity stream design has been made in figma. https://www.figma.com/file/uYsmFIA0eHKg63wWICI326/574-UI-KIT?type=design&node-id=2124-9969&mode=design&t=OCbsozLF3kULllgJ-0 

<img width="303" alt="Screenshot 2023-12-24 at 02 38 02" src="https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1-mobile/assets/126410955/ecd3527c-5e65-47fe-a09e-fb7d761c2a2d">

For like, unlike, user add, user remove, create story icons: 

import FavoriteIcon from '@mui/icons-material/Favorite';
import StoryIcon from '@mui/icons-material/Article';
import CommentIcon from '@mui/icons-material/Comment';
import PersonAddIcon from '@mui/icons-material/PersonAdd';
import PersonRemoveIcon from '@mui/icons-material/PersonRemove';

such as @oguzsenna used in this branch: 
https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/blob/main/backend/frontend/src/pages/activity/ActivityStream.js
