### ISSUE TITLE
Network manager code clean-up

### ISSUE THREAD

**Issue by mert-aydin** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1-mobile#20]
Some method can be reduced into a single method for clarity.

**Comment by ayhncvdr2** [comment]
@sadikkuzu @mert-aydin new PR is opened: https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1-mobile/pull/24

**Comment by sadikkuzu** [comment]
Crystal clear ✨ 
Thanks for magic improvement! 🚀 

Later on, let's add issue number to the end of commit messages:
https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/wiki/Conventions#for-mobile-repo
