### ISSUE TITLE
Fetch stories from backend

### ISSUE THREAD

**Issue by mert-aydin** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1-mobile#44]
For now, stories are loaded from a json file on the repository. Should make an API call to fetch real stories from our backend.

**Comment by sadikkuzu** [comment]
@mert-aydin hi, 
Could you create a new branch from `feature/21-feed-screen`, and then, go on with this new branch?
`feature/44-fetch-stories`

**Comment by sadikkuzu** [comment]
@ayhncvdr hi, 
Could you create a new branch from `feature/21-feed-screen`, and then, go on with this new branch?
`feature/44-fetch-stories`
