### ISSUE TITLE
Implement story details page

### ISSUE THREAD

**Issue by ayhncvdr2** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1-mobile#55]
stories in home page are ready. create story details page without showing location in map for now. Also, try to make comments section as a bottom sheet. When the user presses a story in home, story details page will be opened.

https://www.figma.com/file/uYsmFIA0eHKg63wWICI326/574-UI-KIT?type=design&node-id=2226-1630&mode=dev

**Warning**: It will be a separate page, so there will be no bottom bar in this page.

**Comment by ayhncvdr2** [comment]
you also need to use html decoder and send comment call to the service. comment call will be like login call, you can use it as a base, for html decode you can use either of these:

https://api.dart.dev/stable/3.1.5/dart-html/dart-html-library.html
https://pub.dev/packages/html

**Comment by mert-aydin** [comment]
done as merged #67
