### ISSUE TITLE
Add golden tests for login

### ISSUE THREAD

**Issue by ayhncvdr** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1-mobile#7]
[golden_toolkit](https://pub.dev/packages/golden_toolkit) contains APIs and utilities that build upon [Flutter's Golden test](https://github.com/flutter/flutter/wiki/Writing-a-golden-file-test-for-package:flutter) functionality to provide powerful UI regression tests.

**Comment by ayhncvdr2** [comment]
flutter test golden_test/ --update-goldens

use the above command to generate screenshots
