### ISSUE TITLE
Remove password validation for login and register

### ISSUE THREAD

**Issue by oguzsenna** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1-mobile#83]
mobile password requires 6 character while web does not require that. Remove this validation from mobile app

**Comment by sadikkuzu** [comment]
@oguzsenna hi,
app is ready for test.
could you please try it via this link:
https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1-mobile/actions/runs/7099948899

![image](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1-mobile/assets/23168063/fda9839e-e544-4ba4-8771-b6e3ba0e3a15)
