### ISSUE TITLE
Implement Activity Stream Page

### ISSUE THREAD

**Issue by ayhncvdr2** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1-mobile#96]
Implement an Activity Stream page for the mobile application, showcasing various user activities. The page will provide insights into interactions such as follows, unfollows, comments, likes, and new story creations. Additionally, upon tapping an activity, users will be redirected to the target user's profile. Furthermore, a PATCH request will be sent to mark the activity as viewed.

**Comment by ckertam** [comment]
To get activity stream you should send a GET API Request to below endpoint
/user/activities

To click on activities you should send GET API Request to below endpoint
/user/activities/{activity.id}

### For the types of the activity you can check below photo
<img width="539" alt="image" src="https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1-mobile/assets/78985396/f639d103-0ae8-4b29-9b00-75e8e2b69c1c">


### response as below

[
    {
        "id": 252,
        "user": 1,
        "user_username": "cano14",
        "activity_type": "new_story",
        "date": "2023-12-13T02:17:01.995482Z",
        "viewed": false,
        "target_user": 3,
        "target_user_username": "sadik1",
        "target_story": 94,
        "target_story_title": "London Alive"
    },
    {
        "id": 233,
        "user": 1,
        "user_username": "cano14",
        "activity_type": "story_liked",
        "date": "2023-12-11T07:33:48.093947Z",
        "viewed": false,
        "target_user": 2,
        "target_user_username": "oguz1",
        "target_story": 24,
        "target_story_title": "Kabak Tatlısı tadında bir gece"
    },
    {
        "id": 231,
        "user": 1,
        "user_username": "cano14",
        "activity_type": "new_commented_on_story",
        "date": "2023-12-11T07:33:41.391341Z",
        "viewed": false,
        "target_user": 2,
        "target_user_username": "oguz1",
        "target_story": 24,
        "target_story_title": "Kabak Tatlısı tadında bir gece"
    },
    {
        "id": 230,
        "user": 1,
        "user_username": "cano14",
        "activity_type": "followed_user",
        "date": "2023-12-11T07:33:04.232647Z",
        "viewed": false,
        "target_user": 2,
        "target_user_username": "oguz1",
        "target_story": null,
        "target_story_title": null
    },
    {
        "id": 226,
        "user": 1,
        "user_username": "cano14",
        "activity_type": "new_commented_on_story",
        "date": "2023-12-11T00:02:06.028941Z",
        "viewed": false,
        "target_user": 6,
        "target_user_username": "aykutk",
        "target_story": 25,
        "target_story_title": "Rainy Day"
    },
    {
        "id": 225,
        "user": 1,
        "user_username": "cano14",
        "activity_type": "followed_user",
        "date": "2023-12-11T00:01:39.260925Z",
        "viewed": false,
        "target_user": 6,
        "target_user_username": "aykutk",
        "target_story": null,
        "target_story_title": null
    },
    {
        "id": 161,
        "user": 1,
        "user_username": "cano14",
        "activity_type": "story_liked",
        "date": "2023-12-06T16:18:28.830478Z",
        "viewed": false,
        "target_user": 21,
        "target_user_username": "asya00",
        "target_story": 83,
        "target_story_title": "111"
    },
    {
        "id": 160,
        "user": 1,
        "user_username": "cano14",
        "activity_type": "followed_user",
        "date": "2023-12-04T21:33:59.327741Z",
        "viewed": false,
        "target_user": 28,
        "target_user_username": "sadik123",
        "target_story": null,
        "target_story_title": null
    },
    {
        "id": 133,
        "user": 1,
        "user_username": "cano14",
        "activity_type": "story_liked",
        "date": "2023-11-30T17:31:27.969576Z",
        "viewed": false,
        "target_user": 3,
        "target_user_username": "sadik1",
        "target_story": 20,
        "target_story_title": "İş Dünyası Ödüllerinde Unutulmaz Bir An"
    },
    {
        "id": 125,
        "user": 1,
        "user_username": "cano14",
        "activity_type": "followed_user",
        "date": "2023-11-29T19:23:38.075154Z",
        "viewed": false,
        "target_user": 27,
        "target_user_username": "oguz2",
        "target_story": null,
        "target_story_title": null
    },
    {
        "id": 122,
        "user": 1,
        "user_username": "cano14",
        "activity_type": "new_commented_on_story",
        "date": "2023-11-29T19:21:59.356389Z",
        "viewed": false,
        "target_user": 2,
        "target_user_username": "oguz1",
        "target_story": 25,
        "target_story_title": "Rainy Day"
    },
    {
        "id": 116,
        "user": 1,
        "user_username": "cano14",
        "activity_type": "new_commented_on_story",
        "date": "2023-11-27T17:00:50.090593Z",
        "viewed": false,
        "target_user": 3,
        "target_user_username": "sadik1",
        "target_story": 25,
        "target_story_title": "Rainy Day"
    },
    {
        "id": 103,
        "user": 1,
        "user_username": "cano14",
        "activity_type": "new_commented_on_story",
        "date": "2023-11-26T20:03:53.571539Z",
        "viewed": false,
        "target_user": 3,
        "target_user_username": "sadik1",
        "target_story": 25,
        "target_story_title": "Rainy Day"
    },
    {
        "id": 102,
        "user": 1,
        "user_username": "cano14",
        "activity_type": "story_liked",
        "date": "2023-11-26T20:03:26.579397Z",
        "viewed": false,
        "target_user": 3,
        "target_user_username": "sadik1",
        "target_story": 25,
        "target_story_title": "Rainy Day"
    },
    {
        "id": 86,
        "user": 1,
        "user_username": "cano14",
        "activity_type": "story_liked",
        "date": "2023-11-21T20:45:48.195349Z",
        "viewed": false,
        "target_user": 6,
        "target_user_username": "aykutk",
        "target_story": 24,
        "target_story_title": "Kabak Tatlısı tadında bir gece"
    },
    {
        "id": 85,
        "user": 1,
        "user_username": "cano14",
        "activity_type": "story_unliked",
        "date": "2023-11-21T20:45:46.260196Z",
        "viewed": false,
        "target_user": 6,
        "target_user_username": "aykutk",
        "target_story": 24,
        "target_story_title": "Kabak Tatlısı tadında bir gece"
    },
    {
        "id": 84,
        "user": 1,
        "user_username": "cano14",
        "activity_type": "story_liked",
        "date": "2023-11-21T20:45:43.601337Z",
        "viewed": false,
        "target_user": 6,
        "target_user_username": "aykutk",
        "target_story": 24,
        "target_story_title": "Kabak Tatlısı tadında bir gece"
    },
    {
        "id": 83,
        "user": 1,
        "user_username": "cano14",
        "activity_type": "unfollowed_user",
        "date": "2023-11-21T20:45:27.790082Z",
        "viewed": false,
        "target_user": 6,
        "target_user_username": "aykutk",
        "target_story": null,
        "target_story_title": null
    },
    {
        "id": 82,
        "user": 1,
        "user_username": "cano14",
        "activity_type": "followed_user",
        "date": "2023-11-21T20:45:26.462564Z",
        "viewed": false,
        "target_user": 6,
        "target_user_username": "aykutk",
        "target_story": null,
        "target_story_title": null
    },
    {
        "id": 17,
        "user": 1,
        "user_username": "cano14",
        "activity_type": "story_liked",
        "date": "2023-11-19T16:55:40.985942Z",
        "viewed": false,
        "target_user": 21,
        "target_user_username": "asya00",
        "target_story": 24,
        "target_story_title": "Kabak Tatlısı tadında bir gece"
    },
    {
        "id": 12,
        "user": 1,
        "user_username": "cano14",
        "activity_type": "new_commented_on_story",
        "date": "2023-11-13T18:33:38.898470Z",
        "viewed": true,
        "target_user": 3,
        "target_user_username": "sadik1",
        "target_story": 24,
        "target_story_title": "Kabak Tatlısı tadında bir gece"
    },
    {
        "id": 10,
        "user": 1,
        "user_username": "cano14",
        "activity_type": "story_liked",
        "date": "2023-11-11T21:11:22.766388Z",
        "viewed": true,
        "target_user": 3,
        "target_user_username": "sadik1",
        "target_story": 22,
        "target_story_title": "Starbucksta Bir Gün"
    },
    {
        "id": 9,
        "user": 1,
        "user_username": "cano14",
        "activity_type": "story_liked",
        "date": "2023-11-11T21:11:10.018356Z",
        "viewed": false,
        "target_user": 3,
        "target_user_username": "sadik1",
        "target_story": 23,
        "target_story_title": "Starbucksta bir gün"
    },
    {
        "id": 8,
        "user": 1,
        "user_username": "cano14",
        "activity_type": "story_unliked",
        "date": "2023-11-11T21:11:08.860736Z",
        "viewed": false,
        "target_user": 3,
        "target_user_username": "sadik1",
        "target_story": 23,
        "target_story_title": "Starbucksta bir gün"
    },
    {
        "id": 7,
        "user": 1,
        "user_username": "cano14",
        "activity_type": "followed_user",
        "date": "2023-11-11T21:10:51.288667Z",
        "viewed": false,
        "target_user": 3,
        "target_user_username": "sadik1",
        "target_story": null,
        "target_story_title": null
    },
    {
        "id": 6,
        "user": 1,
        "user_username": "cano14",
        "activity_type": "unfollowed_user",
        "date": "2023-11-11T21:10:48.966369Z",
        "viewed": false,
        "target_user": 3,
        "target_user_username": "sadik1",
        "target_story": null,
        "target_story_title": null
    },
    {
        "id": 5,
        "user": 1,
        "user_username": "cano14",
        "activity_type": "followed_user",
        "date": "2023-11-11T21:08:06.335638Z",
        "viewed": true,
        "target_user": 3,
        "target_user_username": "sadik1",
        "target_story": null,
        "target_story_title": null
    },
    {
        "id": 4,
        "user": 1,
        "user_username": "cano14",
        "activity_type": "unfollowed_user",
        "date": "2023-11-11T21:08:03.403024Z",
        "viewed": false,
        "target_user": 3,
        "target_user_username": "sadik1",
        "target_story": null,
        "target_story_title": null
    }
]
