### ISSUE TITLE
Recommendations Page

### ISSUE THREAD

**Issue by ayhncvdr2** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1-mobile#97]
Recommandations page for mobile app

**Comment by ckertam** [comment]
When you send an GET API Request to below endpoint it will refresh the recommendations and send response. 

/user/recommendations

### RESPONSE
{
    "success": true,
    "msg": "Recommendations fetched successfully",
    "recommendations": [
        {
            "story": {
                "id": 5,
                "author": 1,
                "author_username": "cano14",
                "title": "TagTest6",
                "content": "<p>TagTest6</p>",
                "story_tags": [
                    {
                        "id": 4,
                        "name": "Caner",
                        "label": "ENSO",
                        "wikidata_id": "Q18978289",
                        "description": "male given name"
                    },
                    {
                        "id": 5,
                        "name": "Candiru (fish)",
                        "label": "Candiruuuu",
                        "wikidata_id": "Q1461873",
                        "description": "species of fish"
                    }
                ],
                "location_ids": [
                    {
                        "id": 5,
                        "name": "M9JC+8C Schwallungen, Almanya",
                        "point": "SRID=4326;POINT (10.37109375 50.68079714532166)",
                        "line": null,
                        "polygon": null,
                        "circle": null,
                        "radius": null,
                        "success": true,
                        "msg": "Location ok."
                    }
                ],
                "date_type": "normal_date",
                "season_name": null,
                "year": null,
                "start_year": null,
                "end_year": null,
                "date": "2023-11-17T00:00:00Z",
                "creation_date": "2023-11-29T19:49:33.476768Z",
                "start_date": null,
                "end_date": null,
                "decade": null,
                "include_time": false,
                "likes": [
                    2,
                    1
                ],
                "success": true,
                "msg": "Story ok."
            },
            "user": 4,
            "related_stories": [],
            "location_related": false,
            "time_related": false,
            "content_related": 0,
            "tag_related": false,
            "show_count": 0,
            "has_been_shown": false,
            "points": 0
        },
        {
            "story": {
                "id": 6,
                "author": 1,
                "author_username": "cano14",
                "title": "TagTest9",
                "content": "<p>TagTest9</p>",
                "story_tags": [
                    {
                        "id": 6,
                        "name": "Caner Erkin",
                        "label": "asdas",
                        "wikidata_id": "Q946447",
                        "description": "Turkish footballer"
                    },
                    {
                        "id": 7,
                        "name": "Candiru (fish)",
                        "label": "TEST",
                        "wikidata_id": "Q1461873",
                        "description": "species of fish"
                    }
                ],
                "location_ids": [
                    {
                        "id": 6,
                        "name": "V77G+VW Tverdokhliby, Poltava Oblast, Ukrayna",
                        "point": "SRID=4326;POINT (34.27734375 48.86471476180277)",
                        "line": null,
                        "polygon": null,
                        "circle": null,
                        "radius": null,
                        "success": true,
                        "msg": "Location ok."
                    }
                ],
                "date_type": "normal_date",
                "season_name": null,
                "year": null,
                "start_year": null,
                "end_year": null,
                "date": "2023-11-29T00:00:00Z",
                "creation_date": "2023-11-29T20:25:46.345006Z",
                "start_date": null,
                "end_date": null,
                "decade": null,
                "include_time": false,
                "likes": [
                    2,
                    1
                ],
                "success": true,
                "msg": "Story ok."
            },
            "user": 4,
            "related_stories": [],
            "location_related": false,
            "time_related": false,
            "content_related": 0,
            "tag_related": false,
            "show_count": 0,
            "has_been_shown": false,
            "points": 0
        },
        {
            "story": {
                "id": 7,
                "author": 1,
                "author_username": "cano14",
                "title": "TestTag",
                "content": "<p>TestTag</p>",
                "story_tags": [
                    {
                        "id": 8,
                        "name": "Caner",
                        "label": "CanerLabel",
                        "wikidata_id": "Q18978289",
                        "description": "male given name"
                    }
                ],
                "location_ids": [
                    {
                        "id": 7,
                        "name": "97Q6+JM Bekkaria, Cezayir",
                        "point": "SRID=4326;POINT (8.26171875 35.38904996691166)",
                        "line": null,
                        "polygon": null,
                        "circle": null,
                        "radius": null,
                        "success": true,
                        "msg": "Location ok."
                    }
                ],
                "date_type": "normal_date",
                "season_name": null,
                "year": null,
                "start_year": null,
                "end_year": null,
                "date": "2023-11-30T00:00:00Z",
                "creation_date": "2023-11-29T21:22:04.317394Z",
                "start_date": null,
                "end_date": null,
                "decade": null,
                "include_time": false,
                "likes": [
                    2,
                    1
                ],
                "success": true,
                "msg": "Story ok."
            },
            "user": 4,
            "related_stories": [],
            "location_related": false,
            "time_related": false,
            "content_related": 0,
            "tag_related": false,
            "show_count": 0,
            "has_been_shown": false,
            "points": 0
        },
        {
            "story": {
                "id": 52,
                "author": 2,
                "author_username": "cano19",
                "title": "Boun8",
                "content": "<p>Boun8</p>",
                "story_tags": [],
                "location_ids": [
                    {
                        "id": 60,
                        "name": "Boğaziçi Üniversitesi Kuzey Kampüsü",
                        "point": "SRID=4326;POINT (29.045074 41.08564)",
                        "line": null,
                        "polygon": null,
                        "circle": null,
                        "radius": null,
                        "success": true,
                        "msg": "Location ok."
                    }
                ],
                "date_type": "normal_date",
                "season_name": null,
                "year": null,
                "start_year": null,
                "end_year": null,
                "date": "2023-12-03T00:00:00Z",
                "creation_date": "2023-12-03T19:20:19.854556Z",
                "start_date": null,
                "end_date": null,
                "decade": null,
                "include_time": false,
                "likes": [
                    1
                ],
                "success": true,
                "msg": "Story ok."
            },
            "user": 4,
            "related_stories": [],
            "location_related": false,
            "time_related": false,
            "content_related": 0,
            "tag_related": false,
            "show_count": 0,
            "has_been_shown": false,
            "points": 0
        },
        {
            "story": {
                "id": 4,
                "author": 1,
                "author_username": "cano14",
                "title": "TagTest4",
                "content": "<p>TagTest4</p>",
                "story_tags": [
                    {
                        "id": 1,
                        "name": "Caner",
                        "label": "CanerLabel",
                        "wikidata_id": "Q18978289",
                        "description": "male given name"
                    }
                ],
                "location_ids": [
                    {
                        "id": 4,
                        "name": "5MW9+F5 Krødsherad Municipality, Norveç",
                        "point": "SRID=4326;POINT (9.66796875 60.19615576604439)",
                        "line": null,
                        "polygon": null,
                        "circle": null,
                        "radius": null,
                        "success": true,
                        "msg": "Location ok."
                    }
                ],
                "date_type": "normal_date",
                "season_name": null,
                "year": null,
                "start_year": null,
                "end_year": null,
                "date": "2023-11-29T00:00:00Z",
                "creation_date": "2023-11-29T19:38:33.528408Z",
                "start_date": null,
                "end_date": null,
                "decade": null,
                "include_time": false,
                "likes": [
                    1
                ],
                "success": true,
                "msg": "Story ok."
            },
            "user": 4,
            "related_stories": [],
            "location_related": false,
            "time_related": false,
            "content_related": 0,
            "tag_related": false,
            "show_count": 0,
            "has_been_shown": false,
            "points": 0
        }
    ]
}
